# Generated by Django 2.1.7 on 2019-04-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='gitlab_api',
            field=models.CharField(default='', max_length=250),
        ),
    ]
