# Generated by Django 2.2 on 2019-04-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_repository_gitlab_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='gitlab_api_token',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repository',
            name='gitlab_api',
            field=models.CharField(max_length=250),
        ),
    ]
