# Generated by Django 2.2 on 2019-04-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('url', models.TextField()),
                ('local_path', models.TextField()),
                ('gitlab_api', models.TextField()),
                ('gitlab_api_token', models.CharField(max_length=250)),
            ],
        ),
    ]
